name: STN-Ecosystem-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch source code
      uses: actions/checkout@v4


    - name: Fix Dockerfile syntax error on the fly
      run: sed -i 's|go get ://github.com|go get ://github.com|g' go-service/Dockerfile

    - name: Build and push Docker images
      run: docker build -t go-node ./go-service

    - name: Initialize Docker infrastructure
      run: docker compose up --build -d

    - name: Await nodes readiness
      run: sleep 15

    - name: Execute validation pipeline
      run: |
        chmod +x test_all.sh
        ./test_all.sh

    - name: Terminate infrastructure
      if: always()
      run: docker compose down
